# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 14:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=16)),
                ('lastname', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('registration_date', models.DateField(default=datetime.datetime(2017, 3, 31, 14, 8, 15, 968521, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm', models.CharField(max_length=16)),
                ('model', models.CharField(max_length=16)),
                ('type_of_transmission', models.BooleanField()),
                ('path_to_image', models.FilePathField()),
                ('status', models.BooleanField()),
                ('price', models.IntegerField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(default=datetime.datetime(2017, 3, 31, 14, 8, 15, 970804, tzinfo=utc))),
                ('amount', models.IntegerField(max_length=16)),
                ('acount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Acount')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Car')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20, unique=True)),
                ('espire', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Acount')),
            ],
        ),
    ]
