# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 14:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20170331_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acount',
            name='registration_date',
            field=models.DateField(default=datetime.datetime(2017, 3, 31, 14, 12, 20, 187832, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2017, 3, 31, 14, 12, 20, 190080, tzinfo=utc)),
        ),
    ]
