# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 14:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20170331_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acount',
            name='registration_date',
            field=models.DateField(default=datetime.datetime(2017, 3, 31, 14, 36, 43, 527647, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2017, 3, 31, 14, 36, 43, 530079, tzinfo=utc)),
        ),
        migrations.AlterModelTable(
            name='acount',
            table='Acount',
        ),
        migrations.AlterModelTable(
            name='car',
            table='Car',
        ),
        migrations.AlterModelTable(
            name='order',
            table='Order',
        ),
        migrations.AlterModelTable(
            name='session',
            table='Session',
        ),
    ]
