# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 14:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20170331_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acount',
            name='registration_date',
            field=models.DateField(default=datetime.datetime(2017, 3, 31, 14, 40, 53, 425125, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2017, 3, 31, 14, 40, 53, 428034, tzinfo=utc)),
        ),
    ]
