# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 07:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20170331_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='path_to_image',
        ),
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='acount',
            name='registration_date',
            field=models.DateField(default=datetime.datetime(2017, 4, 1, 7, 45, 8, 328077, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2017, 4, 1, 7, 45, 8, 331930, tzinfo=utc)),
        ),
    ]
