# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 08:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_auto_20170401_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acount',
            name='registration_date',
            field=models.DateField(default=datetime.datetime(2017, 4, 1, 8, 48, 29, 902026, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2017, 4, 1, 8, 48, 29, 904857, tzinfo=utc)),
        ),
    ]
