# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0020_auto_20170401_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acount',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
