# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0021_auto_20170402_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(height_field=380, null=True, upload_to='images/', width_field=600),
        ),
    ]
