# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0022_auto_20170402_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image_height',
            field=models.PositiveIntegerField(default=380),
        ),
        migrations.AddField(
            model_name='car',
            name='image_width',
            field=models.PositiveIntegerField(default=600),
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(height_field='image_height', null=True, upload_to='images/', width_field='image_width'),
        ),
    ]
