# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0023_auto_20170402_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='car',
            name='image_width',
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
