# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 03:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0024_auto_20170402_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='acount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Acount',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
